/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectdb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class emp extends javax.swing.JFrame {

    /**
     * Creates new form emp
     */
    int id;
    public emp() {
        initComponents();
         deleteb.setVisible(false);
        updateb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        number2 = new javax.swing.JTextField();
        number3 = new javax.swing.JTextField();
        number4 = new javax.swing.JTextField();
        number5 = new javax.swing.JTextField();
        number6 = new javax.swing.JTextField();
        addb = new javax.swing.JButton();
        searchb = new javax.swing.JButton();
        deleteb = new javax.swing.JButton();
        updateb = new javax.swing.JButton();
        exitb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Harrington", 3, 36)); // NOI18N
        jLabel16.setText("Employee");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\44911d955df77a82e556b723de24d690.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 510));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setText("extra hours:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setText("IDNO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setText("email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 50, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setText("salary:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setText("DNO:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel8.setText("EEID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        text1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });
        getContentPane().add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 220, 30));

        number2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });
        getContentPane().add(number2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 220, 30));

        number3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });
        getContentPane().add(number3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 220, 30));

        number4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });
        getContentPane().add(number4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 220, 30));

        number5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });
        getContentPane().add(number5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 220, 30));

        number6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });
        getContentPane().add(number6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 220, 30));

        addb.setBackground(new java.awt.Color(153, 153, 255));
        addb.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        addb.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\icons8-add-16.png")); // NOI18N
        addb.setText("add");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });
        getContentPane().add(addb, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 110, -1));

        searchb.setBackground(new java.awt.Color(153, 153, 255));
        searchb.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        searchb.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\icons8-search-16.png")); // NOI18N
        searchb.setText("search");
        searchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbActionPerformed(evt);
            }
        });
        getContentPane().add(searchb, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 110, -1));

        deleteb.setBackground(new java.awt.Color(153, 153, 255));
        deleteb.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        deleteb.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\icons8-delete-16.png")); // NOI18N
        deleteb.setText("delete");
        deleteb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebActionPerformed(evt);
            }
        });
        getContentPane().add(deleteb, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 110, -1));

        updateb.setBackground(new java.awt.Color(153, 153, 255));
        updateb.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        updateb.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\icons8-available-updates-16.png")); // NOI18N
        updateb.setText("update");
        updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebActionPerformed(evt);
            }
        });
        getContentPane().add(updateb, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 110, -1));

        exitb.setBackground(new java.awt.Color(255, 0, 0));
        exitb.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        exitb.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\exit.png")); // NOI18N
        exitb.setText("exit");
        exitb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbActionPerformed(evt);
            }
        });
        getContentPane().add(exitb, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text1ActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number2ActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number3ActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number4ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number5ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number6ActionPerformed

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        // TODO add your handling code here:

        try{

            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:XE";
            Connection con=DriverManager.getConnection(url, "c##yazann", "654321");

            con.setAutoCommit(false);
         //   Statement stmt=con.createStatement();
         
         String sql="";
         if (number6.getText().equals(""))
         {
               sql="insert into employee values (EMP_SEQ.NEXTVAL,'"+text1.getText()
           +"',"+Integer.parseInt(number2.getText())+","+Integer.parseInt(number3.getText())+","+Integer.parseInt(number4.getText())
           +","+Integer.parseInt(number5.getText())+",null)";
         
         }
         else{  sql="insert into employee values (EMP_SEQ.NEXTVAL,'"+text1.getText()
           +"',"+Integer.parseInt(number2.getText())+","+Integer.parseInt(number3.getText())+","+Integer.parseInt(number4.getText())
           +","+Integer.parseInt(number5.getText())+","+Integer.parseInt(number6.getText())+")"; 
  
         }
            PreparedStatement ps=con.prepareStatement(sql);
            ps.executeUpdate();
            text1.setText("");
            number2.setText("");
            number3.setText("");
            number4.setText("");
            number5.setText("");
            number6.setText("");
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null,"done");
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString(),"message",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addbActionPerformed

    private void searchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbActionPerformed
        // TODO add your handling code here:
        
        deleteb.setVisible(true);
        updateb.setVisible(true);
        boolean flag=false;
        id=Integer.parseInt(JOptionPane.showInputDialog("EID"));
        try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:XE";
            Connection con=DriverManager.getConnection(url, "c##yazann", "654321");
            con.setAutoCommit(false);
            String sql="select * from employee where eid=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setInt(1,id );
            ResultSet rs=ps.executeQuery();
            if (rs.next())
            {
                flag=true;
                text1.setText(rs.getString("EMAIL"));
                number2.setText(rs.getInt("SALARY")+"");
                number3.setText(rs.getInt("EXTRA_HOURS")+"");
                number4.setText(rs.getInt("IDNO")+"");
                number5.setText(rs.getInt("DNO")+"");
                number6.setText(rs.getInt("EEID")+"");
                if (number6.getText().equals("0"))
                    number6.setText("");
                con.commit();
                con.close();
            }
            if(!flag)
            JOptionPane.showMessageDialog(null,"dose not exist");

        }

        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString(),"message",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_searchbActionPerformed

    private void deletebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebActionPerformed
        // TODO add your handling code here:
         deleteb.setVisible(false);
         updateb.setVisible(false);
        
        try{
            String sql="delete from employee where EID="+id+"";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:XE";
            Connection con=DriverManager.getConnection(url, "c##yazann", "654321");
            con.setAutoCommit(false);
            PreparedStatement ps=con.prepareStatement(sql);
            ps.execute();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null,"done");

            text1.setText("");
            number2.setText("");
            number3.setText("");
            number4.setText("");
            number5.setText("");
            number6.setText("");

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString(),"message",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_deletebActionPerformed

    private void updatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebActionPerformed
        // TODO add your handling code here:
        
        deleteb.setVisible(false);
        updateb.setVisible(false);
        try{
            String sql="update employee set EMAIL='"+text1.getText()+"',salary="+Integer.parseInt(number2.getText())+",EXTRA_HOURS="+Integer.parseInt(number3.getText())+","
            + "IDNO="+Integer.parseInt(number4.getText())+",DNO="+Integer.parseInt(number5.getText())+",EEID="+Integer.parseInt(number6.getText())+" where eid="+id+"";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:XE";
            Connection con=DriverManager.getConnection(url, "c##yazann", "654321");
            con.setAutoCommit(false);
            PreparedStatement ps=con.prepareStatement(sql);
            ps.execute();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null,"done");

            text1.setText("");
            number2.setText("");
            number3.setText("");
            number4.setText("");
            number5.setText("");
            number6.setText("");
           
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString(),"message",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_updatebActionPerformed

    private void exitbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_exitbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addb;
    private javax.swing.JButton deleteb;
    private javax.swing.JButton exitb;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField number2;
    private javax.swing.JTextField number3;
    private javax.swing.JTextField number4;
    private javax.swing.JTextField number5;
    private javax.swing.JTextField number6;
    private javax.swing.JButton searchb;
    private javax.swing.JTextField text1;
    private javax.swing.JButton updateb;
    // End of variables declaration//GEN-END:variables
}
