/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectdb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class project extends javax.swing.JFrame {

    /**
     * Creates new form project
     */  int id;
    public project() {
      
        initComponents();
       updateb.setVisible(false);
       deleteb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        year1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        month1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        day1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        year2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        month2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        day2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        number3 = new javax.swing.JTextField();
        addb = new javax.swing.JButton();
        searchb = new javax.swing.JButton();
        updateb = new javax.swing.JButton();
        deleteb = new javax.swing.JButton();
        exitb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Harrington", 3, 36)); // NOI18N
        jLabel16.setText("Project");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\project-delivery.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 70, -1, 32));

        text1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        getContentPane().add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 70, 189, 32));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("location:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 140, 70, 32));

        text2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        text2.setForeground(new java.awt.Color(51, 0, 0));
        getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 140, 189, 32));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("start date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, -1, 30));

        jLabel7.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setText("year:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, -1, 20));

        year1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        year1.setForeground(new java.awt.Color(51, 0, 0));
        getContentPane().add(year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 240, 40, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 0));
        jLabel8.setText("month:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 240, -1, -1));

        month1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        month1.setForeground(new java.awt.Color(51, 0, 0));
        getContentPane().add(month1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 240, 40, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setText("day:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 240, -1, -1));

        day1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        day1.setForeground(new java.awt.Color(51, 0, 0));
        getContentPane().add(day1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 240, 40, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("end date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, -1, 38));

        jLabel10.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setText("year:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 330, -1, 30));

        year2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        year2.setForeground(new java.awt.Color(51, 0, 0));
        getContentPane().add(year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 330, 40, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 0));
        jLabel11.setText("month:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 330, -1, -1));

        month2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        month2.setForeground(new java.awt.Color(51, 0, 0));
        getContentPane().add(month2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 330, 40, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 0));
        jLabel12.setText("day:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 330, -1, 20));

        day2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        day2.setForeground(new java.awt.Color(51, 0, 0));
        getContentPane().add(day2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 330, 40, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("dno:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 400, -1, 32));

        number3.setColumns(5);
        number3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        number3.setForeground(new java.awt.Color(51, 0, 0));
        getContentPane().add(number3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 400, -1, 32));

        addb.setBackground(new java.awt.Color(153, 153, 255));
        addb.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        addb.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\icons8-add-16.png")); // NOI18N
        addb.setText("add");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });
        getContentPane().add(addb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 460, 110, -1));

        searchb.setBackground(new java.awt.Color(153, 153, 255));
        searchb.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        searchb.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\icons8-search-16.png")); // NOI18N
        searchb.setText("search");
        searchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbActionPerformed(evt);
            }
        });
        getContentPane().add(searchb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 460, 110, -1));

        updateb.setBackground(new java.awt.Color(153, 153, 255));
        updateb.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        updateb.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\icons8-available-updates-16.png")); // NOI18N
        updateb.setText("update");
        updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebActionPerformed(evt);
            }
        });
        getContentPane().add(updateb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 500, 110, -1));

        deleteb.setBackground(new java.awt.Color(153, 153, 255));
        deleteb.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        deleteb.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\icons8-delete-16.png")); // NOI18N
        deleteb.setText("delete");
        deleteb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebActionPerformed(evt);
            }
        });
        getContentPane().add(deleteb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 500, 110, -1));

        exitb.setBackground(new java.awt.Color(255, 0, 0));
        exitb.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        exitb.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\projectdb\\src\\main\\java\\com\\mycompany\\projectdb\\exit.png")); // NOI18N
        exitb.setText("exit");
        exitb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbActionPerformed(evt);
            }
        });
        getContentPane().add(exitb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 540, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        // TODO add your handling code here:

        try{
            String year1t,month1t,day1t,start,year2t,month2t,day2t,end;
            year1t=year1.getText();
            month1t=month1.getText();
            day1t=day1.getText();
            start=year1t+"/"+month1t+"/"+day1t;
            year2t=year2.getText();
            month2t=month2.getText();
            day2t=day2.getText();
            end=year2t+"/"+month2t+"/"+day2t;

            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:XE";
            Connection con=DriverManager.getConnection(url, "c##yazann", "654321");

            con.setAutoCommit(false);
            //   Statement stmt=con.createStatement();


            String sql="insert into project values (P_SEQ.NEXTVAL,'"+text1.getText()
                +"','"+text2.getText()+"','"+start+"','"+end
                +"',"+Integer.parseInt(number3.getText())+")";

            
            PreparedStatement ps=con.prepareStatement(sql);
            ps.executeUpdate();
            text1.setText("");
            text2.setText("");
            number3.setText("");
            year1.setText("");
            month1.setText("");
            day1.setText("");
            year2.setText("");
            month2.setText("");
            day2.setText("");            
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null,"done");
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString(),"message",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addbActionPerformed

    private void searchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbActionPerformed
        // TODO add your handling code here:
        
        boolean flag=false;
         
        id=Integer.parseInt(JOptionPane.showInputDialog("PNO"));
        try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:XE";
            Connection con=DriverManager.getConnection(url, "c##yazann", "654321");
            con.setAutoCommit(false);
            String sql="select * from project where PNO=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setInt(1,id );
              String arr1[];
              String arr2[];
            ResultSet rs=ps.executeQuery();
            if (rs.next())
            {
                flag=true;
                text1.setText(rs.getString("P_NAME"));
                text2.setText(rs.getString("P_LOCATION"));
                number3.setText(rs.getInt("DNO")+"");
                arr1=rs.getString("START_DATE").split("/");
                year1.setText(arr1[0]);
                month1.setText(arr1[1]);
                day1.setText(arr1[2]);
                 arr2=rs.getString("END_DATE").split("/");
                year2.setText(arr2[0]);
                month2.setText(arr2[1]);
                day2.setText(arr2[2]);
                con.commit();
                con.close();
            }
            if(!flag)
            JOptionPane.showMessageDialog(null,"dose not exist");
      

        }

        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString(),"message",JOptionPane.WARNING_MESSAGE);
        }
        updateb.setVisible(true);
        deleteb.setVisible(true);
    }//GEN-LAST:event_searchbActionPerformed

    private void updatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebActionPerformed
        // TODO add your handling code here:
       

        try{
                        String year1t,month1t,day1t,start,year2t,month2t,day2t,end;
            year1t=year1.getText();
            month1t=month1.getText();
            day1t=day1.getText();
            start=year1t+"/"+month1t+"/"+day1t;
            year2t=year2.getText();
            month2t=month2.getText();
            day2t=day2.getText();
            end=year2t+"/"+month2t+"/"+day2t;
            
            String sql="update project set P_NAME='"+text1.getText()+"',P_LOCATION='"+text2.getText()+"',START_DATE='"+start+"',"
            + "END_DATE='"+end+"',DNO="+Integer.parseInt(number3.getText())+"where pno="+id+"";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:XE";
            Connection con=DriverManager.getConnection(url, "c##yazann", "654321");
            con.setAutoCommit(false);
            PreparedStatement ps=con.prepareStatement(sql);
            ps.execute();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null,"done");

            text1.setText("");
            text2.setText("");
            number3.setText("");
            year1.setText("");
            month1.setText("");
            day1.setText("");
            year2.setText("");
            month2.setText("");
            day2.setText("");

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString(),"message",JOptionPane.WARNING_MESSAGE);
        }
 updateb.setVisible(false);
        deleteb.setVisible(false);
    }//GEN-LAST:event_updatebActionPerformed

    private void deletebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebActionPerformed
        // TODO add your handling code here:

        try{
            String sql="delete from project where PNO="+id+"";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:XE";
            Connection con=DriverManager.getConnection(url, "c##yazann", "654321");
            con.setAutoCommit(false);
            PreparedStatement ps=con.prepareStatement(sql);
            ps.execute();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null,"done");

            text1.setText("");
            text2.setText("");
            number3.setText("");
            year1.setText("");
            month1.setText("");
            day1.setText("");
            year2.setText("");
            month2.setText("");
            day2.setText("");

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString(),"message",JOptionPane.WARNING_MESSAGE);
        }
        updateb.setVisible(false);
        deleteb.setVisible(false);

    }//GEN-LAST:event_deletebActionPerformed

    private void exitbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_exitbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addb;
    private javax.swing.JTextField day1;
    private javax.swing.JTextField day2;
    private javax.swing.JButton deleteb;
    private javax.swing.JButton exitb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField month1;
    private javax.swing.JTextField month2;
    private javax.swing.JTextField number3;
    private javax.swing.JButton searchb;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JButton updateb;
    private javax.swing.JTextField year1;
    private javax.swing.JTextField year2;
    // End of variables declaration//GEN-END:variables
}
